project_id = "opmqfcwykqqocwsmoclc"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
port = 54323
ip_version = "ipv4"

[storage]
enabled = true
port = 54324
file_size_limit = "50MiB"
image_transformation = {enabled = true}

[auth]
enabled = true
port = 54325
site_url = "http://localhost:5173"
additional_redirect_urls = ["https://localhost:5173"]
jwt_expiry = 3600
enable_signup = true
enable_confirmations = false

[functions.send-booking-confirmation]
verify_jwt = false